/**
 * Companies + jobs seed — creates 2 companies with 5 active jobs each.
 *
 * Mirrors the production company-onboarding flow:
 *   1. Owner user is created exactly like `authService.createUser` does for a
 *      company_owner registration (same field set as the signup form in
 *      `frontend/src/pages/auth/Register.tsx`).
 *   2. Company is created with the same minimal payload the signup uses
 *      (`name`, `slug`, `approval_status: 'pending'`), then "completed" with
 *      the editable fields exposed by the Company Profile form
 *      (`frontend/src/pages/company/Profile.tsx`): description, industry,
 *      company_size, website_url, linkedin_url, logo_url.
 *   3. Approval is flipped to `approved` to mirror an admin moderation
 *      action — without this the company won't surface in the public feeds.
 *
 * Field-set parity:
 *   - Industry values use the Profile form's capitalized list
 *     (Technology, Healthcare, Finance, Education, Manufacturing, Retail,
 *     Media, Transportation, Real Estate, Other) rather than free-form
 *     strings.
 *   - `company_size` values match the Company schema enum
 *     (`1-10`, `11-50`, `51-200`, `201-500`, `500+`).
 *   - `founding_year` is intentionally omitted — it's not in either form.
 *
 * Run with: npx tsx src/scripts/seed-companies.ts
 *
 * Safe to re-run:
 *   - Companies are matched by `slug` and reused if already present.
 *   - Owner users matched by email and reused.
 *   - Branches matched by (company_id, name) and reused.
 *   - Jobs matched by (company_id, title) and reused.
 *
 * Each job is back-dated within the last 14 days so they show up in the
 * "Companies hiring near you" home-feed section out of the box.
 */

import 'dotenv/config';
import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../config/database.js';
import {
  User,
  Company,
  CompanyBranch,
  Job,
  JobSkill,
  SkillTag,
  JobCategory,
} from '../models/index.js';

interface JobSeed {
  title: string;
  description: string;
  responsibilities: string;
  requirements: string;
  experience_level: 'entry' | 'mid' | 'senior' | 'lead' | 'executive';
  experience_min_years: number;
  experience_max_years: number;
  job_type: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance';
  work_mode: 'onsite' | 'remote' | 'hybrid';
  salary_min: number;
  salary_max: number;
  salary_currency: string;
  category: string;
  required_skills: string[];
  optional_skills: string[];
  posted_days_ago: number;
}

/**
 * Industry options mirror the Company Profile form. Anything outside this set
 * won't appear correctly in the form's <select>, so we constrain seeds to it.
 */
type Industry =
  | 'Technology'
  | 'Healthcare'
  | 'Finance'
  | 'Education'
  | 'Manufacturing'
  | 'Retail'
  | 'Media'
  | 'Transportation'
  | 'Real Estate'
  | 'Other';

/** Company.company_size enum from the Mongoose schema. */
type CompanySize = '1-10' | '11-50' | '51-200' | '201-500' | '500+';

interface CompanySeed {
  /** Sent by the signup form as `company_name`. */
  name: string;
  /** Auto-generated by `authService.createUser` from the name; pinned here so
   *  re-runs deterministically find the same company. */
  slug: string;
  /** From the Company Profile form. */
  industry: Industry;
  /** From the Company Profile form. */
  company_size: CompanySize;
  /** From the Company Profile form. */
  description: string;
  /** From the Company Profile form (`website` field, persisted as `website_url`). */
  website_url: string;
  /** From the Company Profile form (`linkedIn` field, persisted as `linkedin_url`). */
  linkedin_url?: string;
  /** From the Company Profile form (uploaded via `companyEndpoints.uploadLogo`). */
  logo_url?: string;
  /** Mirrors the auth signup payload (email + password). */
  owner: { email: string; password: string };
  /** Branches are managed separately by the company; not part of the signup or
   *  Profile form. We seed one default branch so jobs can be located. */
  branch: {
    name: string;
    city: string;
    state: string;
    country: string;
    address: string;
    latitude: number;
    longitude: number;
  };
  jobs: JobSeed[];
}

const companies: CompanySeed[] = [
  {
    name: 'Razorpay',
    slug: 'razorpay',
    industry: 'Finance',
    company_size: '500+',
    description:
      'Razorpay is a full-stack financial solutions company that helps businesses accept, process, and disburse payments at scale.',
    website_url: 'https://razorpay.com',
    linkedin_url: 'https://www.linkedin.com/company/razorpay',
    owner: { email: 'owner@razorpay.example.com', password: 'Owner@1234' },
    branch: {
      name: 'Razorpay HQ — Bengaluru',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      address: 'SJR Cyber, Laskar Hosur Road, Bengaluru 560030',
      latitude: 12.9279,
      longitude: 77.6271,
    },
    jobs: [
      {
        title: 'Senior Full-Stack Engineer',
        description:
          'Own end-to-end features on the merchant dashboard. Work across React, Node.js services, and Postgres. You will partner with PMs and designers and lead technical decisions for your area.',
        responsibilities:
          '• Design and implement user-facing features\n• Mentor 2 junior engineers\n• Drive code quality through reviews and tech-debt initiatives',
        requirements:
          '5+ years of professional software engineering experience. Strong React + TypeScript on the frontend, Node.js + Postgres on the backend. Experience leading projects end-to-end.',
        experience_level: 'senior',
        experience_min_years: 5,
        experience_max_years: 9,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 3500000,
        salary_max: 5500000,
        salary_currency: 'INR',
        category: 'Software Engineering',
        required_skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
        optional_skills: ['AWS', 'Docker'],
        posted_days_ago: 2,
      },
      {
        title: 'Staff Backend Engineer — Payments',
        description:
          'Lead the design of high-throughput payment ingestion services. Set the technical direction for the team handling 50M+ daily transactions.',
        responsibilities:
          '• Architect critical payment flows\n• Drive performance and reliability initiatives\n• Mentor senior engineers',
        requirements:
          '8+ years building backend systems. Deep expertise in Go or Java. Strong distributed-systems and database fundamentals. Prior on-call leadership.',
        experience_level: 'lead',
        experience_min_years: 8,
        experience_max_years: 14,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 6500000,
        salary_max: 9500000,
        salary_currency: 'INR',
        category: 'Software Engineering',
        required_skills: ['Go', 'System Design', 'PostgreSQL', 'Kafka'],
        optional_skills: ['AWS', 'Kubernetes'],
        posted_days_ago: 5,
      },
      {
        title: 'Frontend Engineer (React)',
        description:
          'Build the next generation of merchant onboarding flows in React. Deeply collaborative role with design and product.',
        responsibilities:
          '• Ship pixel-perfect, accessible React UIs\n• Work with design on prototypes and reviews\n• Contribute to the internal component library',
        requirements:
          '2-4 years of React experience. Solid TypeScript, CSS, accessibility fundamentals. Bonus: testing-library experience.',
        experience_level: 'mid',
        experience_min_years: 2,
        experience_max_years: 4,
        job_type: 'full_time',
        work_mode: 'remote',
        salary_min: 1600000,
        salary_max: 2600000,
        salary_currency: 'INR',
        category: 'Software Engineering',
        required_skills: ['React', 'TypeScript', 'CSS', 'HTML'],
        optional_skills: ['Tailwind CSS', 'Jest'],
        posted_days_ago: 8,
      },
      {
        title: 'DevOps Engineer',
        description:
          'Own the deployment platform and CI/CD pipelines. Build the infra that lets 200+ engineers ship safely several times a day.',
        responsibilities:
          '• Operate the production Kubernetes platform\n• Improve CI pipelines, observability, and alerting\n• Participate in the on-call rotation',
        requirements:
          '4+ years in DevOps / SRE roles. Production AWS, Kubernetes, Terraform. Comfortable scripting in Python or Go.',
        experience_level: 'senior',
        experience_min_years: 4,
        experience_max_years: 8,
        job_type: 'full_time',
        work_mode: 'onsite',
        salary_min: 3000000,
        salary_max: 5000000,
        salary_currency: 'INR',
        category: 'DevOps & Infrastructure',
        required_skills: ['AWS', 'Kubernetes', 'Terraform', 'Docker'],
        optional_skills: ['Python', 'Linux'],
        posted_days_ago: 11,
      },
      {
        title: 'Data Scientist — Risk',
        description:
          'Build models that detect payment fraud in real time. Partner with Risk and Engineering to ship features behind low-latency APIs.',
        responsibilities:
          '• Train and evaluate fraud detection models\n• Productionize models with engineering\n• Establish model performance monitoring',
        requirements:
          '3+ years of applied ML, ideally on fraud or risk problems. Strong Python + SQL. Familiarity with PyTorch or scikit-learn.',
        experience_level: 'mid',
        experience_min_years: 3,
        experience_max_years: 6,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 2500000,
        salary_max: 4200000,
        salary_currency: 'INR',
        category: 'Data & Analytics',
        required_skills: ['Python', 'Machine Learning', 'SQL'],
        optional_skills: ['PyTorch', 'AWS'],
        posted_days_ago: 13,
      },
    ],
  },
  {
    name: 'Swiggy',
    slug: 'swiggy',
    industry: 'Transportation',
    company_size: '500+',
    description:
      'Swiggy is India’s leading on-demand convenience platform, delivering food, groceries, and household essentials to millions of users every day.',
    website_url: 'https://www.swiggy.com',
    linkedin_url: 'https://www.linkedin.com/company/swiggy-in',
    owner: { email: 'owner@swiggy.example.com', password: 'Owner@1234' },
    branch: {
      name: 'Swiggy Tech Center — Hyderabad',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      address: 'HITEC City, Hyderabad 500081',
      latitude: 17.4435,
      longitude: 78.3772,
    },
    jobs: [
      {
        title: 'Senior Software Engineer — Logistics',
        description:
          'Work on the dispatch and delivery routing systems. Optimize order assignment for hundreds of thousands of partners.',
        responsibilities:
          '• Design dispatch algorithms\n• Build resilient services in Java\n• Drive latency and reliability improvements',
        requirements:
          '5+ years of backend engineering. Strong Java, distributed systems, and queueing fundamentals. Comfortable with on-call.',
        experience_level: 'senior',
        experience_min_years: 5,
        experience_max_years: 9,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 3200000,
        salary_max: 5200000,
        salary_currency: 'INR',
        category: 'Software Engineering',
        required_skills: ['Java', 'System Design', 'PostgreSQL', 'Kafka'],
        optional_skills: ['AWS', 'Redis'],
        posted_days_ago: 1,
      },
      {
        title: 'Android Engineer',
        description:
          'Build the consumer Android app used by tens of millions of users. Focus on performance, accessibility, and feature velocity.',
        responsibilities:
          '• Ship features in Kotlin / Jetpack Compose\n• Optimize app startup and rendering performance\n• Partner with backend on API design',
        requirements:
          '3+ years of Android development. Production Kotlin and Jetpack Compose. Care for app performance and crash-free rates.',
        experience_level: 'mid',
        experience_min_years: 3,
        experience_max_years: 6,
        job_type: 'full_time',
        work_mode: 'onsite',
        salary_min: 1800000,
        salary_max: 3200000,
        salary_currency: 'INR',
        category: 'Mobile Engineering',
        required_skills: ['Kotlin', 'Android', 'Java'],
        optional_skills: ['Firebase', 'Git'],
        posted_days_ago: 4,
      },
      {
        title: 'SRE / Platform Engineer',
        description:
          'Own the multi-region Kubernetes platform powering Swiggy’s services. Improve developer experience and reliability.',
        responsibilities:
          '• Operate production Kubernetes clusters\n• Build platform tooling and abstractions\n• Drive incident response improvements',
        requirements:
          '4+ years SRE / Platform. Strong Kubernetes, Terraform, AWS. Programming fluency in Go or Python.',
        experience_level: 'senior',
        experience_min_years: 4,
        experience_max_years: 8,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 3000000,
        salary_max: 5000000,
        salary_currency: 'INR',
        category: 'DevOps & Infrastructure',
        required_skills: ['Kubernetes', 'AWS', 'Terraform', 'Linux'],
        optional_skills: ['Go', 'Python'],
        posted_days_ago: 7,
      },
      {
        title: 'Data Scientist — Recommendations',
        description:
          'Improve the home-feed recommendation models for the Swiggy app. Iterate fast and measure impact via online A/B tests.',
        responsibilities:
          '• Train and evaluate ranking models\n• Set up A/B experiments and read results\n• Collaborate with engineering on serving',
        requirements:
          '2+ years of applied ML. Strong Python + SQL. Bonus: NLP or recommendations experience.',
        experience_level: 'mid',
        experience_min_years: 2,
        experience_max_years: 5,
        job_type: 'full_time',
        work_mode: 'hybrid',
        salary_min: 2200000,
        salary_max: 3800000,
        salary_currency: 'INR',
        category: 'Data & Analytics',
        required_skills: ['Python', 'Machine Learning', 'SQL'],
        optional_skills: ['PyTorch', 'NLP'],
        posted_days_ago: 9,
      },
      {
        title: 'QA Engineer / SDET',
        description:
          'Build and maintain end-to-end test automation for the consumer apps. Catch regressions before they ship.',
        responsibilities:
          '• Design and own automation suites in Playwright / Appium\n• Drive CI test reliability\n• Partner with feature teams on test strategy',
        requirements:
          '3+ years of QA experience, with at least 1 year of automation. Comfort with JavaScript or TypeScript and CI systems.',
        experience_level: 'mid',
        experience_min_years: 3,
        experience_max_years: 6,
        job_type: 'full_time',
        work_mode: 'onsite',
        salary_min: 1400000,
        salary_max: 2400000,
        salary_currency: 'INR',
        category: 'Quality Assurance',
        required_skills: ['Selenium', 'Playwright', 'JavaScript'],
        optional_skills: ['Manual Testing', 'JIRA'],
        posted_days_ago: 12,
      },
    ],
  },
];

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

async function getOrCreateSkillTag(name: string): Promise<mongoose.Types.ObjectId> {
  const existing = await SkillTag.findOne({ name });
  if (existing) return existing._id as mongoose.Types.ObjectId;
  const created = await SkillTag.create({ name, slug: slugify(name) });
  return created._id as mongoose.Types.ObjectId;
}

async function getOrCreateJobCategory(name: string): Promise<mongoose.Types.ObjectId> {
  const existing = await JobCategory.findOne({ name });
  if (existing) return existing._id as mongoose.Types.ObjectId;
  const created = await JobCategory.create({ name, slug: slugify(name) });
  return created._id as mongoose.Types.ObjectId;
}

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

async function seed(): Promise<void> {
  console.log('Seeding companies + jobs...\n');
  await connectDatabase();

  let companiesCreated = 0;
  let jobsCreated = 0;
  let jobsSkipped = 0;

  for (const c of companies) {
    // === Step 1: signup ===
    // Mirror authService.createUser for role=company_owner. The signup form
    // collects email + password + company_name (+ industry, which the auth
    // schema currently strips). We set is_email_verified=true here only
    // because seeds shouldn't require an email round-trip.
    let owner = await User.findOne({ email: c.owner.email });
    if (!owner) {
      const password_hash = await bcrypt.hash(c.owner.password, 12);
      owner = await User.create({
        email: c.owner.email,
        password_hash,
        role: 'company_owner',
        is_email_verified: true,
        is_active: true,
        is_banned: false,
        totp_enabled: false,
      });
      console.log(`  + Owner   ${c.owner.email}`);
    } else {
      console.log(`  - Owner   ${c.owner.email}  (already exists)`);
    }

    // Companies are created with the same minimal payload that
    // authService.createUser uses: { name, slug, approval_status: 'pending' }.
    // The Profile form fills in everything else after signup.
    let company = await Company.findOne({ slug: c.slug });
    let createdNow = false;
    if (!company) {
      company = await Company.create({
        name: c.name,
        slug: c.slug,
        approval_status: 'pending',
      });
      companiesCreated++;
      createdNow = true;
      console.log(`  + Company [${c.name}]  (signup payload)`);
    } else {
      console.log(`  - Company [${c.name}]  (already exists)`);
    }

    if (!owner.company_id) {
      owner.company_id = company._id as mongoose.Types.ObjectId;
      await owner.save();
    }

    if (createdNow) {
      // === Step 2: Profile-form fields ===
      // Same shape the company owner would submit via /company/profile.
      await Company.updateOne(
        { _id: company._id },
        {
          $set: {
            description: c.description,
            industry: c.industry,
            company_size: c.company_size,
            website_url: c.website_url,
            linkedin_url: c.linkedin_url,
            logo_url: c.logo_url,
          },
        }
      );

      // === Step 3: admin approval ===
      // Mirrors adminApi.approveCompany so the company is visible in seeker
      // search and home-feed nearby aggregations.
      await Company.updateOne(
        { _id: company._id },
        { $set: { approval_status: 'approved', approved_at: new Date() } }
      );
      // Reload so subsequent steps see the merged document.
      company = await Company.findById(company._id);
      if (!company) throw new Error(`Failed to reload company ${c.slug} after update`);
      console.log(`    profile filled + approved`);
    }

    // Branch
    let branch = await CompanyBranch.findOne({
      company_id: company._id,
      name: c.branch.name,
    });
    if (!branch) {
      branch = await CompanyBranch.create({
        company_id: company._id,
        name: c.branch.name,
        city: c.branch.city,
        state: c.branch.state,
        country: c.branch.country,
        address: c.branch.address,
        latitude: c.branch.latitude,
        longitude: c.branch.longitude,
        is_active: true,
      });
      console.log(`  + Branch  ${c.branch.name}`);
    } else {
      console.log(`  - Branch  ${c.branch.name}  (already exists)`);
    }

    // Jobs
    for (const j of c.jobs) {
      const existingJob = await Job.findOne({ company_id: company._id, title: j.title });
      if (existingJob) {
        console.log(`    - Job    ${j.title}  (already exists)`);
        jobsSkipped++;
        continue;
      }

      const categoryId = await getOrCreateJobCategory(j.category);

      const slug = `${slugify(j.title)}-${Math.random().toString(36).slice(2, 7)}`;
      const created = await Job.create({
        company_id: company._id,
        category_id: categoryId,
        posted_by: owner._id,
        job_ref: `${c.slug.toUpperCase()}-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
        title: j.title,
        slug,
        description: j.description,
        responsibilities: j.responsibilities,
        requirements: j.requirements,
        experience_level: j.experience_level,
        experience_min_years: j.experience_min_years,
        experience_max_years: j.experience_max_years,
        job_type: j.job_type,
        work_mode: j.work_mode,
        salary_min: j.salary_min,
        salary_max: j.salary_max,
        salary_currency: j.salary_currency,
        salary_disclosed: true,
        openings: 1,
        locations: [
          {
            branch_id: branch._id,
            label: `${c.branch.name} — ${c.branch.city}`,
            latitude: c.branch.latitude,
            longitude: c.branch.longitude,
            city: c.branch.city,
            state: c.branch.state,
            country: c.branch.country,
            address: c.branch.address,
            openings: 1,
            is_primary: true,
            geo: { type: 'Point', coordinates: [c.branch.longitude, c.branch.latitude] },
          },
        ],
        status: 'active',
        views_count: 0,
      });

      // Back-date so the home-feed nearby aggregation can find it
      const postedAt = daysAgo(j.posted_days_ago);
      await Job.updateOne({ _id: created._id }, { $set: { createdAt: postedAt, updatedAt: postedAt } });

      // Required + optional skills
      for (const skillName of j.required_skills) {
        const tagId = await getOrCreateSkillTag(skillName);
        try {
          await JobSkill.create({ job_id: created._id, skill_tag_id: tagId, is_required: true });
        } catch {
          // unique conflict — already linked
        }
      }
      for (const skillName of j.optional_skills) {
        const tagId = await getOrCreateSkillTag(skillName);
        try {
          await JobSkill.create({ job_id: created._id, skill_tag_id: tagId, is_required: false });
        } catch {
          // unique conflict — already linked
        }
      }

      console.log(`    + Job    ${j.title.padEnd(40)}  posted ${j.posted_days_ago}d ago`);
      jobsCreated++;
    }
  }

  console.log(
    `\n  Done -- ${companiesCreated} companies created (others skipped), ${jobsCreated} jobs created, ${jobsSkipped} jobs skipped.\n`
  );

  console.log('  Company-owner credentials:');
  for (const c of companies) {
    console.log(`    ${c.name.padEnd(10)}  ${c.owner.email}  /  ${c.owner.password}`);
  }
  console.log('');

  await disconnectDatabase();
}

seed().catch((err) => {
  console.error('Company seed failed:', err);
  mongoose.disconnect();
  process.exit(1);
});
